version: '3.8'

# TODO env файл куда нужно поместить всю секретную информауию такой файл не надо пушить на гитхаб

services:
  # Neo4j Service
  neo4j:
    image: neo4j:community
    container_name: neo4j
    ports:
      - "7474:7474"  # Neo4j Browser
      - "7687:7687"  # Bolt-протокол
    environment:
      - NEO4J_AUTH=neo4j/mypassword  # Логин/пароль
    volumes:
      - neo4j_data:/data  # Сохранение данных
    restart: unless-stopped

  # Zookeeper Service (для Kafka)
#  zookeeper:
#    image: confluentinc/cp-zookeeper:7.3.1
#    container_name: zookeeper
#    ports:
#      - "2181:2181"
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#      ZOOKEEPER_SYNC_LIMIT: 2
#    restart: unless-stopped
#
#  # Kafka Service
#  kafka:
#    image: confluentinc/cp-kafka:7.3.1
#    container_name: kafka
#    depends_on:
#      - zookeeper
#    ports:
#      - "9092:9092"
#      - "9093:9093"
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#    restart: unless-stopped
#
#  # Kafka UI
#  kafka-ui:
#    image: provectuslabs/kafka-ui:latest
#    container_name: kafka-ui
#    depends_on:
#      - kafka
#    ports:
#      - "8080:8080"  # Веб-интерфейс будет доступен на http://localhost:8080
#    environment:
#      KAFKA_CLUSTERS_0_NAME: local-kafka
#      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
#      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
#      KAFKA_CLUSTERS_0_JMXPORT: 9999
#      DYNAMIC_CONFIG_ENABLED: "true"
#    restart: unless-stopped
#
#  # Redis Service
#  redis:
#    image: redis:7.2
#    container_name: redis-container
#    ports:
#      - "6380:6379"
#    command: ["redis-server", "--appendonly", "yes"]
#    volumes:
#      - redis-data:/data
#    restart: unless-stopped

volumes:
  neo4j_data:
