spring.application.name=Gateway
server.port = 8082

server.max-http-request-header-size=16384

advertisement.service.address = http://localhost:8090
user.service.address = http://localhost:8081
admin.service.address = http://localhost:8091